Handle multiple roots generated in main()
Summary:
We were facing issues like:

```
/tmp/tmpav2irf2b/source.c:145:44: error: ‘rd_3’ was not declared in this scope
  145 |     SE_TARGET_STATE(!parse_content(content,rd_3));
      |                                            ^~~~
```

This happened when we had a string + reader being used in main. finalize() only returned the former. Now, we return a list and handle both of them.

Reviewed By: joshsaxe

Differential Revision: D56090345

fbshipit-source-id: 00a6dead5369d1770202a8a8bdd9cfdc78361e06